app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/Spring
    username: postgres
    password: root
    pool-size: 30
#
#server:
#  port: 8080
#
#springdoc:
#  use-management-port: true
#
#management:
#  server:
#    port: 9090
#  endpoints:
#    web:
#      exposure:
#        include: openapi, swaggerui